evenement_platform_affichage:
    path:     /evenement/affichage
    defaults: { _controller: EvenementPlatformBundle:Evenement:affichage }
evenement_platform_affichageArticle:
    path:     /evenement/affichage/article
    defaults: { _controller: EvenementPlatformBundle:Evenement:affichageArticle }