<?php

namespace User\PlatformBundle\Repository;

/**
 * imageUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageUserRepository extends \Doctrine\ORM\EntityRepository
{
}
