user_platform_homepage:
    path:     /
    defaults: { _controller: UserPlatformBundle:Default:index }


user_platform_connexion:
    path:     /connexion
    defaults: { _controller: UserPlatformBundle:User:afficheConnexionFront }

user_platform_testConnexion:
    path:     /album
    defaults: { _controller: UserPlatformBundle:User:connexionFront }

user_platform_monAlbum:
    path:     /mon/album
    defaults: { _controller: UserPlatformBundle:User:affichephotoFront }

user_platform_deconnexion:
    path:     /deconnexion
    defaults: { _controller: UserPlatformBundle:User:deconnexionFront }
