user_platform_homepage:
    path:     /
    defaults: { _controller: UserPlatformBundle:Default:index }


user_platform_connexion:
    path:     /connexion
    defaults: { _controller: UserPlatformBundle:User:afficheConnexionFront }
