accueil_platform_admin:
    resource: "@AccueilPlatformBundle/Resources/config/routing_admin.yml"
    prefix:   /administrateur

accueil_platform:
    resource: "@AccueilPlatformBundle/Resources/config/routing.yml"
    prefix:   /


user_platform:
    resource: "@UserPlatformBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

