# app/config/security.yml

imports:
    - { resource: "@UserPlatformBundle/Resources/config/security.yml" }

security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:            # Required
        # Examples:
