presentation_platform_affichage:
    path:     /presentation/affichage
    defaults: { _controller: PresentationPlatformBundle:Presentation:affichage }

presentation_platform_modification:
    path:     /presentation/modification
    defaults: { _controller: PresentationPlatformBundle:Presentation:modification }

