<?php

namespace Evenement\PlatformBundle\Repository;

/**
 * imageEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
