contact_platform_affichage:
    path:     /contact/affichage
    defaults: { _controller: ContactPlatformBundle:Contact:affichage }

contact_platform_modification:
    path:     /contact/modification
    defaults: { _controller: ContactPlatformBundle:Contact:modification }